# Variables
EXE = isos_inject

# Rules and targets
all: build

build:
	@cd src && $(MAKE)
	@cp -f src/$(EXE) ./

clean:
	@cd src && $(MAKE) clean
	@rm -f $(EXE)

backup:
	@cd src && $(MAKE) backup

help:
	@echo "Usage:"
	@echo " make [all]\t\tBuild"
	@echo " make build\t\tBuild the software"
	@echo " make backup\t\tRestore the date executable"
	@echo " make clean\t\tRemove all files generated by make"
	@echo " make help\t\tDisplay this help"
	
.PHONY: all build check clean backup help 